language: csharp

sudo: false

install:
  - nuget install nunit.runners -OutputDirectory bin
  - NUNIT=`find bin -name nunit-console.exe`
  - nuget restore */*.sln

script: 
  - xbuild */*.sln
  - mono $NUNIT $(find . -path "*/test-src/bin/*_Test.dll")
